### ISSUE TITLE
if you are okay can you add this paper either?

### ISSUE THREAD

**Issue by himhan34** [DoongLi/awesome-FMCW-LiDAR#2]
https://sites.google.com/view/heliprdataset/home?authuser=0

this dataset also uses aeva fmcw lidar for the data

**Comment by DoongLi** [comment]
Hi, thx for your suggestions, I have already added. Have a great day!

**Comment by himhan34** [comment]
thanks for your consideration! 
have a nice day!

**Comment by himhan34** [comment]
hello!? 
new paper has relased !!
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10772126&tag=1

thanks always. 
best regards

**Comment by DoongLi** [comment]
I have added this paper.

**Comment by DoongLi** [comment]
Hi saehan, do you have time to help maintain this repo? I can add you as an organizer for this repository.

**Comment by himhan34** [comment]
@DoongLi why not, if you are okay. Add me as a maintainer for this repo
