### ISSUE TITLE
Where can I see FMCW-LIO: A Robust Doppler Aided LiDAR-Inertial Odometry? I haven't found it on IEEE or Google Scholar

### ISSUE THREAD

**Issue by HelloDuoLA** [DoongLi/awesome-FMCW-LiDAR#4]
Where can I see FMCW-LIO: A Robust Doppler Aided LiDAR-Inertial Odometry? I haven't found it on IEEE or Google Scholar

**Comment by DoongLi** [comment]
https://scholar.google.com/citations?view_op=view_citation&hl=zh-CN&user=Glqv2ooAAAAJ&sortby=pubdate&citation_for_view=Glqv2ooAAAAJ:tHtfpZlB6tUC
https://www.youtube.com/watch?v=CKj4ihKs8aI&t=5s
The paper does not seem to be public yet.

**Comment by DoongLi** [comment]
I close the comment, and if you have any questions, you can continue to leave a message below or send an email to me.

**Comment by DoongLi** [comment]
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10518074 FMCW-LIO's paper link.

**Comment by HelloDuoLA** [comment]
Thank you for your reply.
